### ISSUE TITLE
mm2_get_global_netblocks has syntax errors

### ISSUE THREAD

**Issue by nirik** [fedora-infra/mirrormanager2#165]
From the monthy crons on mm-backend01:

Subject: Cron <mirrormanager@mm-backend01> cd /usr/share/mirrormanager2 && /usr/bin/mm2_get_global_netblocks /var/lib/mirrormanager/global_netblocks.txt
Date: Sun,  1 May 2016 00:48:04 +0000 (UTC)

basename: missing operand
Try 'basename --help' for more information.
/tmp/get_global_netblocks.HkpbiVzv/: Is a directory
basename: missing operand
Try 'basename --help' for more information.
bzcat: Input file /tmp/get_global_netblocks.HkpbiVzv/ is a directory.
short file (empty packet) at zebra-dump-parser/zebra-dump-parser.pl line 98.

**Comment by adrianreber** [comment]
I think this is the same problem which was fixed in the mm2_get_internet2_netblocks a few months ago. The script tries to extract the current month to download the global netblocks of the current month. The internet2 case has shown, that the servers providing those files do not run on UTC but on local time, so that at 00:48 2016-05-01 the netblock server was probably still in April. I will provide a fix.

**Comment by adrianreber** [comment]
So this error will probably appear again on the 1st of June if we do not install the latest version of MirrorManager in the next five days. Not sure if it is necessary.
