### ISSUE TITLE
RFE: Requesting mirrormanager setup for Fedora ELN

### ISSUE THREAD

**Issue by sgallagher** [fedora-infra/mirrormanager2#382]
The Fedora ELN project is migrating away from its current home on https://odcs.fedoraproject.org/ to hosting on https://dl.fedoraproject.org/pub/eln/

As part of this effort, we'd like to enroll with MirrorManager as a new module (similar to EPEL).

**Comment by abompard** [comment]
Sure! What repositories do you want there? I see:
- AppStream
- BaseOS
- CRB
- Extras
- HighAvailability
- NFV
- RT
- ResilientStorage
- SAP
- SAPHANA

Should we make separate repositories from each of those?

**Comment by sgallagher** [comment]
Yes, please do.

**Comment by abompard** [comment]
If I understand correctly, ELN does not have a "version" in the same sense that Fedora or EPEL have versions, correct?
Should we use those components as versions or does it not make sense?

**Comment by sgallagher** [comment]
I don’t think that makes sense. They’re just extra repos, nothing related
to versioning.

**Comment by abompard** [comment]
OK. I don't think we can have repositories that don't have a version in the current code. What do you think @adrianreber ?

**Comment by sgallagher** [comment]
What is the purpose of the version in mirror-manager? If we *must* have a version, can it be arbitrary? Does it ever actually need to increase? What does changing the number mean?

**Comment by adrianreber** [comment]
Looking at the tree this is not something the code expects. Also having the repositories directly after /eln/ is not something we expect.

**Comment by adrianreber** [comment]
Currently the code expects a layout like epel at least. We would need /eln/eln-version/. Everything else requires code changes. I also think except for rawhide we expect the version to be one or multiple digits.

**Comment by adrianreber** [comment]
> What is the purpose of the version in mirror-manager? If we *must* have a version, can it be arbitrary?

Yes

> Does it ever actually need to increase?

No

> What does changing the number mean?

Nothing. There is just the expectation to be a version.

**Comment by sgallagher** [comment]
Does the version need to be numeric? Could I just add a symlink to the current directory like:
```
lrwxrwxrwx. 1 ftpsync ftpsync  1 Sep 11 09:46 0 -> .
```

That way you can just use the version of zero and I can keep the structure at the top level.

**Comment by sgallagher** [comment]
You didn't answer my question about whether they need to be numeric.

**Comment by adrianreber** [comment]
> You didn't answer my question about whether they need to be numeric.

Yes it needs to be numeric, that is the current regex to figure out the version from the path:  `r"/(([\.\d]+)([-_]\w+)?)/"`

**Comment by sgallagher** [comment]
So, if I just make the path `/pub/eln/0/{BaseOS|AppStream|etc.}` that should be sufficient as a workaround?

Or I could do `73` which "kind of" looks like "EL" upside-down...

**Comment by adrianreber** [comment]
That looks exactly like epel and I would say that should just work.

**Comment by sgallagher** [comment]
OK, we talked about it and decided to use `1` as the version:

https://pagure.io/pungi-fedora/pull-request/1373

**Comment by abompard** [comment]
OK I *think* everything is in place, but the mirror metalink has no mirrors currently:
```
$ curl -s "https://mirrors.fedoraproject.org/metalink?repo=eln-appstream-1&arch=x86_64&country=global"  
<?xml version="1.0" encoding="utf-8"?>
<metalink version="3.0" xmlns="http://www.metalinker.org/" type="dynamic" pubdate="Mon, 16 Sep 2024 07:52:37 GMT" generator="mirrormanager" xmlns:mm0="http://fedorahosted.org/mirrormanager">
 <files>
  <file name="repomd.xml">
   <mm0:timestamp>1726283471</mm0:timestamp>
   <size>2046</size>
   <verification>
    <hash type="md5">3844b3ca80f1d2c110fa23a8d344c563</hash>
    <hash type="sha1">6e4d1b06789df65e2c5fdbdbe3627211af4b5d3f</hash>
    <hash type="sha256">a01f7cb3bff2fb2d61684d8345d99b5b37e5156c927f5af8913215fa4797aa54</hash>
    <hash type="sha512">fa7d14cb95fb1b6093100e54a023eb64d8f6935b2044a033c8a538c1595f35d7a0404e1de7fc02f60a4843771494f8afefa6a7bfbaad9ec0a5e91010efce010a</hash>
   </verification>
   <mm0:alternates>
    <mm0:alternate>
      <mm0:timestamp>1726110622</mm0:timestamp>
      <size>2046</size>
      <verification>
       <hash type="md5">f98bb663f5e189876c7ab6bd563ce9cb</hash>
       <hash type="sha1">6894d0cb1825537b1e6988427ae19924185c079b</hash>
       <hash type="sha256">e56e099a44ba7d01096295c4b4c855f63a9b1f1b5b3f0734a9cb265f9582d75b</hash>
       <hash type="sha512">0ffae782e1dd8e705dc96ced880fbe36751b7ac37e067371de2ef0f8eddd701f71210eddc7ad24c9787cad55f17b39cb99a182ea0cc6172281b18e0aebd5a165</hash>
      </verification>
    </mm0:alternate>
   </mm0:alternates>
   <resources maxconnections="1">
   </resources>
  </file>
 </files>
</metalink>
```

I *think* it's normal, the `dl.fedoraproject.org` host is probably excluded from the mirrorlist results, no?

So, the next step would be to get some mirrors to add the `Fedora ELN` category in Mirrormanager (and actually mirror the content obviously).

**Comment by abompard** [comment]
Yeah, I mean it's excluded from the mirror list in mirrorlist-server, no?
Oh, looking at other repos, I'm apparently wrong. I've probably missed something else in the DB. I'll fix it.

**Comment by abompard** [comment]
Alright, I was missing the HostCategoryUrl. It looks like it's working now!

```
$ curl -s "https://mirrors.fedoraproject.org/metalink?repo=eln-appstream-1&arch=x86_64&country=global"  
<?xml version="1.0" encoding="utf-8"?>
<metalink version="3.0" xmlns="http://www.metalinker.org/" type="dynamic" pubdate="Mon, 16 Sep 2024 14:05:02 GMT" generator="mirrormanager" xmlns:mm0="http://fedorahosted.org/mirrormanager">
 <files>
  <file name="repomd.xml">
   <mm0:timestamp>1726456208</mm0:timestamp>
   <size>2046</size>
   <verification>
    <hash type="md5">8a7e5548e16016431ce0c34fad48e63a</hash>
    <hash type="sha1">1750551f2cef694930512223a73e7f9f3daa43f7</hash>
    <hash type="sha256">cffc1696d807abbedfaa9dde000b019c66df6b0250521ccee142d8f3b28ec4f2</hash>
    <hash type="sha512">944ab9819d8b3e29b65f4082fac545b1647408b1ca5e24cedca4712efd9c19756053926237ece58cd82441935e7e0c90fbb50d2a766f6fbb8bf5493afbda1faa</hash>
   </verification>
   <mm0:alternates>
    <mm0:alternate>
      <mm0:timestamp>1726283471</mm0:timestamp>
      <size>2046</size>
      <verification>
       <hash type="md5">3844b3ca80f1d2c110fa23a8d344c563</hash>
       <hash type="sha1">6e4d1b06789df65e2c5fdbdbe3627211af4b5d3f</hash>
       <hash type="sha256">a01f7cb3bff2fb2d61684d8345d99b5b37e5156c927f5af8913215fa4797aa54</hash>
       <hash type="sha512">fa7d14cb95fb1b6093100e54a023eb64d8f6935b2044a033c8a538c1595f35d7a0404e1de7fc02f60a4843771494f8afefa6a7bfbaad9ec0a5e91010efce010a</hash>
      </verification>
    </mm0:alternate>
   </mm0:alternates>
   <resources maxconnections="1">
    <url protocol="https" type="https" location="US" preference="100">https://dl.fedoraproject.org/pub/eln/1/AppStream/x86_64/os/repodata/repomd.xml</url>
    <url protocol="http" type="http" location="US" preference="100">http://dl.fedoraproject.org/pub/eln/1/AppStream/x86_64/os/repodata/repomd.xml</url>
   </resources>
  </file>
 </files>
</metalink>
```

**Comment by sgallagher** [comment]
OK, something still isn't right here and I'm pretty sure it's on the MirrorManager side:

```
>>> Downloading successful, but checksum doesn't match. Calculated: 53140e258fd2a7f5989faab263cb265a007b8e8766dc0821abce03aa7cb8abfa3cffc5aaf9e204c7b47d350e39c8e3845202
```

If I replace the metalink with a baseurl pointing to dl.fedoraproject.org it works properly, so I think the mirrormanager hashes must be incorrect.

**Comment by abompard** [comment]
I think that's because the fulltimefilelist-eln file that is being update is not the right one (or the one mirrormanager expects). MirrorManager reads `eln/1/fullfiletimelist-eln` and it looks like only `eln/fullfiletimelist-eln` gets updated:

```
$ ls -lrt /srv/pub/eln/1/fullfiletimelist-eln /srv/pub/eln/fullfiletimelist-eln
-rw-r--r--. 1 263 263 6175188 Sep 11 04:09 /srv/pub/eln/1/fullfiletimelist-eln
-rw-r--r--. 1 263 263 6273130 Sep 19 04:09 /srv/pub/eln/fullfiletimelist-eln
```

Could you update `eln/1/fullfiletimelist-eln` and if possible drop `eln/fullfiletimelist-eln` for clarity please?

**Comment by adrianreber** [comment]
I have not been following this closely but I would expect the file in 1/ to be the wrong one if we are scanning eln/. But this probably depends if the config of the scanner points to eln/ or eln/1. My expectation would be that it points at eln/

**Comment by abompard** [comment]
Oh, right, I had to change the location of the filelist in the wrapper because the other one didn't exist at that time, I'll revert it and use the one in `eln/`. Please disregard my comment @sgallagher  (or maybe remove the one in `eln/1`?)

**Comment by abompard** [comment]
Done, the script now points to the proper filelist, and the MM database should be updated. Please test again.

**Comment by sgallagher** [comment]
Testing passed this morning, thanks!

I have deleted the extraneous `/pub/eln/1/fullfilelist*` entries (though I have no idea where they came from...)

**Comment by abompard** [comment]
Cool! :tada: 

> I have deleted the extraneous `/pub/eln/1/fullfilelist*` entries (though I have no idea where they came from...)

I'm guessing it was at the root and was moved with the rest when the `1` directory was created.

**Comment by sgallagher** [comment]
The mirrors aren't working again...

```
Updating and loading repositories:
 Fedora - ELN BaseOS - Developmental packages for the next Enterprise Linux release                                             100% |  39.9 KiB/s |   9.7 KiB |  00m00s
>>> Downloading successful, but checksum doesn't match. Calculated: a68fb0295716199063eb13818e504fd61c4515a53cf19a5178be5d7e9d61eb8b21c780cb38c623975bb39fbdca40dada2507
>>> Downloading successful, but checksum doesn't match. Calculated: a68fb0295716199063eb13818e504fd61c4515a53cf19a5178be5d7e9d61eb8b21c780cb38c623975bb39fbdca40dada2507
>>> Downloading successful, but checksum doesn't match. Calculated: a68fb0295716199063eb13818e504fd61c4515a53cf19a5178be5d7e9d61eb8b21c780cb38c623975bb39fbdca40dada2507
>>> Downloading successful, but checksum doesn't match. Calculated: a68fb0295716199063eb13818e504fd61c4515a53cf19a5178be5d7e9d61eb8b21c780cb38c623975bb39fbdca40dada2507
>>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were triedFailed to download metadata (metalink: "https://mirrors.fedoraproject.org/metalink?repo=eln-baseos-1&arch=x86_64") for repository "eln-baseos"
 Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by sgallagher** [comment]
This is definitely a problem with MirrorManager, as using `dnf5 upgrade --disablerepo=* --repofrompath baseos,https://dl.fedoraproject.org/pub/eln/1/BaseOS/x86_64/os/ --repofrompath appstream,https://dl.fedoraproject.org/pub/eln/1/AppStream/x86_64/os/ --repofrompath crb,https://dl.fedoraproject.org/pub/eln/1/CRB/x86_64/os/` works just fine

**Comment by adrianreber** [comment]
It seems to work again now. This is expected behaviour, kind of. There will also be some time in which the data has been pushed to the primary mirror server but MirrorManager has not scanned the new data.

I cannot see how often the primary mirror is scanned for changes, but as the updated data is only pushed out the mirrorlist servers, which are answering the requests, once per hour, tt will take at least one hour to have up to date data on the mirrorlist servers. In Fedora this is not a problem because we have many mirror servers so as long as the old data is on available on some tier2 mirrors it all works out. For a single mirror setup (only the primary mirror), this will break as you have seen it. Basically every time data is pushed to the primary mirror this can be seen.

For CentOS Stream the scanning happens on a primary mirror that is not public, so we scan the primary mirror before the data is available for anybody else. In theory there also should be some synchronization between MirrorManager and the data being available on the primary mirror, but the current setup seems to work most of the times. For CentOS Stream.

I have seen another thing which will hit you sooner or later with `eln`. The separation of the content in `BaseOS`, `AppStream` and `crb` is something which MirrorManager in the way it is setup of `eln` does not handle correctly. You are not seeing it, yet, because you only have a single mirror, but once there are multiple mirrors you might get content from an older `BaseOS` than the `AppStream` you are using. One of the examples we had when using it with CentOS Stream in the beginning was that `glibc`  from `BaseOS` was a slightly different version than `glibc-devel` from `AppStream`.
This is something that does not happen with Fedora's way of repository setup.

To solve your current problem you need some synchronization between MirrorManager and primary mirror content. CentOS Stream does it with early scanning before the data being public and more mirrors to avoid the problem most of the time.

**Comment by abompard** [comment]
> I cannot see how often the primary mirror is scanned for changes

The ELN category is scanned every 30 minutes [according to the configuration](https://pagure.io/fedora-infra/ansible/blob/main/f/vars/apps/mirrormanager.yml#_74).

**Comment by sgallagher** [comment]
I'm not actually sure what you're proposing here. What exactly does "you need some synchronization between MirrorManager and primary mirror content" mean?

**Comment by adrianreber** [comment]
> > I cannot see how often the primary mirror is scanned for changes
> 
> The ELN category is scanned every 30 minutes [according to the configuration](https://pagure.io/fedora-infra/ansible/blob/main/f/vars/apps/mirrormanager.yml#_74).

The regeneration of the data for the mirrorlist server happens once an hour. The reason for this is that the old code (before rust) could take up to 40 minutes to generate the cache files. Today this is down to 2 or 3 minutes the last time I checked. So we could update the mirrorlist servers much more often and decrease the scanning interval of ELN and also other categories. The problem is that we currently have a relatively stable systems and changing the mirrorlist update interval might bring some new challenges. But we could definitely try it..

**Comment by sgallagher** [comment]
If there's something we can change on ELN's end to make this work better or more safely, I'm willing to do it. I just have no idea what that would require.

**Comment by adrianreber** [comment]
> I'm not actually sure what you're proposing here. What exactly does "you need some synchronization between MirrorManager and primary mirror content" mean?

I am not proposing a real solution because there is not really a way to solve the problem easily. In a perfect world we would scan the primary mirror and update the MirrorManager database. Once the new data is live we would atomically switch the primary mirror from the old to the new content. But that is not really possible.

The problem is that a single mirror system is not something MirrorManager handles well because it was never designed for something like this.

The best way forward would be to see if Fedora Infrastructure can update the mirrorlist server more often. Maybe every 15 minutes. In combination with one or two mirrors it could lead to a situation where the error is handled gracefully by `dnf`.

**Comment by sgallagher** [comment]
We are expecting to gain at least one mirror in the near future; I'll see if I can get the Meta folks to move on that more quickly.

**Comment by nirik** [comment]
FYI, there already is a mirror... 

https://mirrormanager.fedoraproject.org/mirrors/ELN

**Comment by adrianreber** [comment]
Is also added ELN to my mirror.
