### ISSUE TITLE
check metalink alternate repomd code

### ISSUE THREAD

**Issue by nirik** [fedora-infra/mirrormanager2#96]
We need to confirm that the code around handling alternate repomd.xml's is working as expected/desired and that we have the right timeouts on it.

The idea as I understand it is when repomd.xml changes for a repo, we also keep the _old_ repomd.xml as an alternate. Then, after N days we drop that alternate. This allows people to get updates from mirrors with the previous repodata when master has just changed.

However, we have hit situations where we haven't had updates pushes in a while for various reasons (a week or so) and mm seems to drop the _current_ repomd.xml and keep the old/outdated/no longer used alternative one as the only one.

We need to make sure we are dropping the old one, and we need to adjust so that if there's no updates pushes for a while we don't break anything.

**Comment by nirik** [comment]
It looks like we just hit this with rawhide today (2016-05-25). There have not been any rawhide composes that worked for 3 days now and it looks like the last good repomd.xml dropped out. ;( 

We should always try and keep the last one around if there's not a new one...

**Comment by adrianreber** [comment]
I agree that this should be fixed, I think, however, that the failure from yesterday (2016-05-25) was a bit different. The metalink contained a newer timestamp and corresponding checksum then what was available on the filesystem. Not sure what exactly happened, but it seems umdl detected at some point a newer repomd.xml version and did not re-detect the older version but unfortunately removed it from the database.

So we definitely should fix that it should not remove repomd.xml alternative checksums as fast as it does right now. The code looks correctly at [_age_file_details()](../blob/master/mirrormanager2/lib/model.py#L316).

However, we do not define _mirrormanager.max_stale_days_ so that it uses the default value of 3. This means that any alternative checksum is removed after three days. Which seems reasonable if the newly detected repomd.xml checksum is correct. So somehow mirrormanager believed to have detected a new repomd.xml and removed the older checksum after three days. It does not know that the supposedly newer checksum of repomd.xml does no longer exist. On the filesystem was a file from 2016-05-23 with a different checksum than in the metalink (2016-05-24).

There is already an additional guard in the code to have at least two checksum for two days: _mirrormanager.max_propogation_days_ which defaults to two.

So somehow this seems to be triggered by umdl detecting wrong data which is not on the filesystem and thus removing the older checksums after three days, which are however the correct ones.

Increasing both parameters could help, but if umdl detects a newer repomd.xml file during that now longer period will lead to a longer period. Important would be to understand why umdl detected a newer repomd.xml file. Did it actually exist on the filesystem and was then later reverted to the older (probably non-broken version). If this could happen, then we need different logic in umdl to avoid errors like yesterday (2016-05-25).

**Comment by adrianreber** [comment]
Closing as this seems to work.
